<a href="https://colab.research.google.com/github/g0pher98/pytorch-study/blob/main/chap4_pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4.1. 텐서
텐서 : 파이토치 기본단위. GPU 연산 가능

In [1]:
import numpy as np
import torch

x = torch.empty(5, 4)
x

tensor([[5.3829e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [3.5733e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [3.5733e-43, 0.0000e+00, 4.9045e-44, 0.0000e+00]])

`torch.empty()` 메소드를 통해 5x4 빈 tensor를 만들 수 있음. 초기화 되지 않으면 메모리에 남아있던 값이 나옴.

In [6]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.rand(2, 3)

tensor([[0.2065, 0.3269, 0.1896],
        [0.3309, 0.3655, 0.9001]])

In [21]:
# list -> numpy -> tensor
pylist = [[101, 102, 103], [201, 202, 203]]
np_arr = np.array(pylist)

tensor_x = torch.tensor(np_arr)
tensor_x

tensor([[101, 102, 103],
        [201, 202, 203]])

In [22]:
tensor_x.size() # 텐서의 크기

torch.Size([2, 3])

In [24]:
# 파라미터를 넘기거나 크기 데이터의 인덱싱을 이용해서
# Size의 특정 값에 접근할 수 있음
tensor_x.size(0), tensor_x.size()[1] 

(2, 3)

In [25]:
type(tensor)

torch.Tensor

In [39]:
X = torch.rand(3, 4)
Y = torch.rand(3, 4)

X, Y

(tensor([[0.2311, 0.1107, 0.2458, 0.1206],
         [0.2129, 0.7111, 0.1304, 0.5766],
         [0.2014, 0.8471, 0.5790, 0.3286]]),
 tensor([[0.4019, 0.8832, 0.3837, 0.6055],
         [0.8162, 0.4225, 0.4448, 0.8507],
         [0.7307, 0.8227, 0.9568, 0.0853]]))

In [40]:
X+Y == X.add(Y) # numpy처럼 행렬 연산 가능. add처럼 함수로도 가능.

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [41]:
X.add_(Y) # 연산 결과가 X로 덮어씌워짐.
X

tensor([[0.6330, 0.9939, 0.6295, 0.7261],
        [1.0291, 1.1336, 0.5752, 1.4272],
        [0.9322, 1.6698, 1.5358, 0.4140]])

In [46]:
tensor

tensor([[101, 102, 103],
        [201, 202, 203]])

In [47]:
resized_tensor = tensor.view([6])
resized_tensor

tensor([101, 102, 103, 201, 202, 203])

In [49]:
resized_tensor = tensor.view([-1, 2, 1]) # -1은 auto
resized_tensor

tensor([[[101],
         [102]],

        [[103],
         [201]],

        [[202],
         [203]]])

In [52]:
np_array = tensor.numpy()
np_array

array([[101, 102, 103],
       [201, 202, 203]])

In [53]:
type(np_array)

numpy.ndarray

In [62]:
x = torch.ones(1).view(-1,1,1,1,1,1) # 모양이 어떻든
x.item() # 숫자가 하나인 텐서를 텐서4가 아닌 값으로 변환해줌

1.0

# 4.2. 역전파