<a href="https://colab.research.google.com/github/g0pher98/pytorch-study/blob/main/chap4_pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4.1. 텐서
텐서 : 파이토치 기본단위. GPU 연산 가능

In [ ]:
import numpy as np
import torch

x = torch.empty(5, 4)
x

tensor([[5.3829e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [3.5733e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [3.5733e-43, 0.0000e+00, 4.9045e-44, 0.0000e+00]])

`torch.empty()` 메소드를 통해 5x4 빈 tensor를 만들 수 있음. 초기화 되지 않으면 메모리에 남아있던 값이 나옴.

In [ ]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.rand(2, 3)

tensor([[0.2065, 0.3269, 0.1896],
        [0.3309, 0.3655, 0.9001]])

In [ ]:
# list -> numpy -> tensor
pylist = [[101, 102, 103], [201, 202, 203]]
np_arr = np.array(pylist)

tensor_x = torch.tensor(np_arr)
tensor_x

tensor([[101, 102, 103],
        [201, 202, 203]])

In [ ]:
tensor_x.size() # 텐서의 크기

torch.Size([2, 3])

In [ ]:
# 파라미터를 넘기거나 크기 데이터의 인덱싱을 이용해서
# Size의 특정 값에 접근할 수 있음
tensor_x.size(0), tensor_x.size()[1] 

(2, 3)

In [ ]:
type(tensor)

torch.Tensor

In [ ]:
X = torch.rand(3, 4)
Y = torch.rand(3, 4)

X, Y

(tensor([[0.2311, 0.1107, 0.2458, 0.1206],
         [0.2129, 0.7111, 0.1304, 0.5766],
         [0.2014, 0.8471, 0.5790, 0.3286]]),
 tensor([[0.4019, 0.8832, 0.3837, 0.6055],
         [0.8162, 0.4225, 0.4448, 0.8507],
         [0.7307, 0.8227, 0.9568, 0.0853]]))

In [ ]:
X+Y == X.add(Y) # numpy처럼 행렬 연산 가능. add처럼 함수로도 가능.

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
X.add_(Y) # 연산 결과가 X로 덮어씌워짐.
X

tensor([[0.6330, 0.9939, 0.6295, 0.7261],
        [1.0291, 1.1336, 0.5752, 1.4272],
        [0.9322, 1.6698, 1.5358, 0.4140]])

In [ ]:
tensor

tensor([[101, 102, 103],
        [201, 202, 203]])

In [ ]:
resized_tensor = tensor.view([6])
resized_tensor

tensor([101, 102, 103, 201, 202, 203])

In [ ]:
resized_tensor = tensor.view([-1, 2, 1]) # -1은 auto
resized_tensor

tensor([[[101],
         [102]],

        [[103],
         [201]],

        [[202],
         [203]]])

In [ ]:
np_array = tensor.numpy()
np_array

array([[101, 102, 103],
       [201, 202, 203]])

In [ ]:
type(np_array)

numpy.ndarray

In [ ]:
x = torch.ones(1).view(-1,1,1,1,1,1) # 모양이 어떻든
x.item() # 숫자가 하나인 텐서를 텐서4가 아닌 값으로 변환해줌

1.0

# 4.2. 역전파

학습이 잘 되기 위해 모델 파라미터를 최적화하는데, 여기에 사용되는게 미분의 성질을 이용한 역전파.

모델이 복잡해질수록 계산 과정이 복잡해져서 코드를 구현하기에는 어려움이있다. 파이토치는 간단하게 이를 구현할 수 있는 다양한 최적화 방법을 제공한다.

In [27]:
'''
그래디언트 텐서
'''
import torch

# requires_grad : 해당 텐서를 기준으로 모든 연산을 추적
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [28]:
y = x + 1
y

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [29]:
z = 2*(y**2)
z

tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)

In [30]:
r = z.mean()
r

tensor(8., grad_fn=<MeanBackward0>)

In [31]:
r.backward()
x.grad

tensor([[2., 2.],
        [2., 2.]])

`r.backward()`는 r을 기준으로 역전파를 진행하겠다는 의미.
- $r=\frac{z_1+z_2+z_3+z_4}{4}$
- $z_i=2y_i^2=2(x_i+1)^2$
- $\frac{dr}{dx_i}=x_i+1$

따라서 미분 결과는 모두 2가 된다.

In [43]:
'''
자동 미분 - 선형회귀 식
'''
import torch
from matplotlib import pyplot as plt

x = torch.FloatTensor(range(5)).unsqueeze(1) # 2차원으로 reshape
x, x.shape

(tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.]]), torch.Size([5, 1]))

In [44]:
y = 2*x + torch.rand(5, 1)
y

tensor([[0.0674],
        [2.7099],
        [4.8716],
        [6.7741],
        [8.7058]])

In [46]:
# instance가 5개, feature가 1개
num_features = x.shape[1]

In [47]:
# y=wx+b. 일단 초기값은 테스트니까 랜덤으로.
w = torch.randn(num_features, 1, requires_grad=True) # (5,1)
b = torch.randn(1, requires_grad=True)

In [48]:
# 가중치 업데이트는 Stochastic Gradient Descent(SGD) 알고리즘 사용.
optimizer = torch.optim.SGD([w, b], lr=1e-3)